# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hunkr < Formula
  desc "Terminal PR review for humans and agents"
  homepage "https://github.com/wvvb/hunkr"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wvvb/hunkr/releases/download/v0.2.1/hunkr_0.2.1_darwin_amd64.tar.gz"
      sha256 "ae5115ba05d4d046a037b0aa33ff6b79bbe879e04e6acffd050f835e18b964c7"

      define_method(:install) do
        bin.install "hunkr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wvvb/hunkr/releases/download/v0.2.1/hunkr_0.2.1_darwin_arm64.tar.gz"
      sha256 "59ab614a667209957ebe87e4e1b56599a38b146eea7e826678a98521e05fd250"

      define_method(:install) do
        bin.install "hunkr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wvvb/hunkr/releases/download/v0.2.1/hunkr_0.2.1_linux_amd64.tar.gz"
      sha256 "efae05684ee17d72a62d7fd82ec3c9218e7202a87b9b5c19241d774ec86c3212"
      define_method(:install) do
        bin.install "hunkr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wvvb/hunkr/releases/download/v0.2.1/hunkr_0.2.1_linux_arm64.tar.gz"
      sha256 "a4005e7399243223b163150891e7fd9a9432344dcc973a1243882541818baabd"
      define_method(:install) do
        bin.install "hunkr"
      end
    end
  end

  test do
    system "#{bin}/hunkr", "version"
  end
end
