# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hunkr < Formula
  desc "Terminal PR review for humans and agents"
  homepage "https://github.com/wvvb/hunkr"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wvvb/hunkr/releases/download/v0.2.0/hunkr_0.2.0_darwin_amd64.tar.gz"
      sha256 "05f960094da7d57edc72b8d8707fbe31e2acda6546893e768cf89d1433e0c80b"

      define_method(:install) do
        bin.install "hunkr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wvvb/hunkr/releases/download/v0.2.0/hunkr_0.2.0_darwin_arm64.tar.gz"
      sha256 "42efb2481f09001300bd301db71e7e55b8f42a7e2560107f42bacab9981fe1cd"

      define_method(:install) do
        bin.install "hunkr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wvvb/hunkr/releases/download/v0.2.0/hunkr_0.2.0_linux_amd64.tar.gz"
      sha256 "84478b1d1ff61881ccdd24d52e9dade5f72db20a3e231f3a3bd2e59e751cb58b"
      define_method(:install) do
        bin.install "hunkr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wvvb/hunkr/releases/download/v0.2.0/hunkr_0.2.0_linux_arm64.tar.gz"
      sha256 "63ebced335e4065722549a798878f6e646c6071dfa53a4a6ab285c416a945d21"
      define_method(:install) do
        bin.install "hunkr"
      end
    end
  end

  test do
    system "#{bin}/hunkr", "version"
  end
end
